---
os: linux
dist: focal
language: python
python:
  - 3.8

env:
  global:
    - VAGRANT_DEFAULT_PROVIDER: libvirt
    - PY_COLORS: 1
  jobs:
    - MOLECULE_DISTRO: generic/ubuntu1804
    - MOLECULE_DISTRO: generic/debian10

services:
  - docker

cache:
  directories:
    - /home/travis/.vagrant.d/boxes
    - /home/travis/.cache/pipenv

before_install:
  - |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    sudo apt-get update && sudo apt-get install vagrant
    sudo apt-get install -y build-essential qemu-kvm qemu-utils libvirt-dev libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager dnsmasq
    CONFIGURE_ARGS="with-libvirt-include=/usr/share/libvirt with-libvirt-lib=/usr/lib64" sudo vagrant plugin install vagrant-libvirt
  - |
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3
    sudo -H pip3 install --upgrade --ignore-installed --requirement requirements.txt
    sudo -H ansible-galaxy collection install community.crypto

script:
  - sudo -E molecule test
